# Generated by Django 5.1.3 on 2024-11-12 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_franchise_created_by_and_more'),
        ('core', '0002_lead_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_created_by', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='technicians', to='accounts.employee'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('bank', 'Bank Transfer')], max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
                ('recieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by', to='accounts.employee')),
            ],
        ),
    ]
