# Generated by Django 5.1.3 on 2024-11-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faq_remove_sitevisit_visit_notes_quotation_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='sitepicandnotes',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='site_pics/'),
        ),
    ]
