# Generated by Django 5.1.3 on 2024-11-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_account',
            new_name='is_staff',
        ),
    ]
