# Generated by Django 5.1.3 on 2024-11-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_account_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='maritial_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=100),
        ),
    ]
