# Generated by Django 5.1.3 on 2024-11-09 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_maritial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('sale_manager', 'Sale Manager'), ('sales_executive', 'Sales Executive'), ('technical_manager', 'Technical Manager'), ('technician_executive', 'Technician Executive'), ('accounts', 'Accounts')], max_length=100),
        ),
    ]
