# Generated by Django 5.1.3 on 2024-11-11 18:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employee_franchise_remove_employee_role_and_more'),
        ('core', '0002_lead_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='password',
        ),
        migrations.AddField(
            model_name='franchise',
            name='dob',
            field=models.DateField(default='2024-10-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='interests',
            field=models.ManyToManyField(related_name='franchise_interests', to='core.product'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='sales_region',
            field=models.CharField(default='North Region', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='tnc',
            field=models.TextField(default='This is a term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='type',
            field=models.CharField(default='Other', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='gst_number',
            field=models.FileField(upload_to='franchise/gst', validators=[accounts.models.validate_pdf]),
        ),
    ]
