# Generated by Django 5.1.3 on 2024-11-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_employee_neighbours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar_back',
            field=models.ImageField(blank=True, null=True, upload_to='employee/aadhar/back'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhar_front',
            field=models.ImageField(blank=True, null=True, upload_to='employee/aadhar/front'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='driving_license_front',
            field=models.ImageField(blank=True, null=True, upload_to='employee/driving_license/front'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='employee/pan_card'),
        ),
    ]
